.TH BINMAN\-HTML 1                   2016\-02\-28                            5.1.0
.SH NAME
.PP
binman\-html \- HTML manpage from header comment
.SH SYNOPSIS
.PP
\fB\fCbinman\-html\fR [\fIOPTION\fP]... [\fIFILE\fP]
.SH DESCRIPTION
.PP
Extracts the "embedded manpage source", described in 
.BR binman-text (1), 
from the
given \fIFILE\fP or STDIN and transforms it into HTML for use in a web browser.
.SH SEE ALSO
.PP
.BR binman-text (1), 
.BR binman-roff (1), 
.BR binman (1)
