.TH BINMAN 1                        2016\-02\-28                            5.1.0
.SH NAME
.PP
binman \- deprecated; use binman\-* instead
.SH SYNOPSIS
.PP
\fB\fCbinman\fR [\fIOPTION\fP]... \fICOMMAND\fP
.SH DESCRIPTION
.PP
Runs the fellow "\fB\fCbinman\fR\-\fICOMMAND\fP" programs listed under "Commands" below.
.PP
.RS
Note: This program is deprecated for removal in the next major version. To
prepare yourself, please run the fellow binman\-* programs directly instead.
.RE
.SH OPTIONS
.TP
\fB\fC\-h\fR [\fIPATTERN\fP], \fB\fC\-\-help\fR [\fIPATTERN\fP]
Show this help manual and optionally search for \fIPATTERN\fP regular expression.
.SH COMMANDS
.TP
\fB\fCtext\fR ...
Runs 
.BR binman-text (1).
.TP
\fB\fCroff\fR ...
Runs 
.BR binman-roff (1).
.TP
\fB\fChtml\fR ...
Runs 
.BR binman-html (1).
.TP
\fB\fCshow\fR ...
Runs 
.BR binman-show (1).
.TP
\fB\fChelp\fR ...
Runs 
.BR binman-help (1).
.SH SEE ALSO
.PP
.BR binman-rake (1)
